name: ProtonMail Bridge CI/CD
on:
  pull_request:
    types: [ closed ]
  push:
    branches-ignore:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    if: github.event.pull_request.merged
    runs-on: ubuntu-20.04
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Read config file
        id: config_file
        uses: juliangruber/read-file-action@v1
        with:
          path: ./ha-protonmail-bridge/config.json
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Publish to Docker Hub
        uses: home-assistant/builder@2021.01.1
        with:
          args: |
            --docker-hub-check \
            --target ha-protonmail-bridge \
            --amd64 \
            --armv7
      -
        name: Update Docker Hub description armv7
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: fboulay/ha-protonmail-bridge-armv7
          readme-filepath: ./ha-protonmail-bridge/DOCS.md
      -
        name: Update Docker Hub description amd64
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: fboulay/ha-protonmail-bridge-amd64
          readme-filepath: ./ha-protonmail-bridge/DOCS.md
      -
        name: Git tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ fromJSON(steps.config_file.outputs.content).version }}",
              sha: context.sha
            })
  shellcheck:
    name: Run Shellcheck
    runs-on: ubuntu-20.04
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
  hadolint:
    name: Run hadolint
    runs-on: ubuntu-20.04
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Run hadolint
        uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: ./ha-protonmail-bridge/Dockerfile
