name: Publish Docker image
on:
  pull_request:
    types: [ closed ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    if: github.event.pull_request.merged
    runs-on: ubuntu-20.04
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Read config file
        id: config_file
        run: |
          content=`cat ./ha-protonmail-bridge/config.json`
          echo "::set-output name=file::$content"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Publish to Docker Hub
        uses: home-assistant/builder@2021.01.1
        with:
          args: |
            --docker-hub-check \
            --target ha-protonmail-bridge \
            --amd64 \
            --armv7
      -
        name: Git tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{fromJson(steps.config_file.outputs.file).version}}",
              sha: context.sha
            })
